constraints:
  max_sped_per_section: 3
  max_teacher_sections: 6
  special_courses:
    Heroes Teach:
      allowed_periods:
      - R2
      - G2
      max_seats: 15
      requires_dedicated_teacher: true
    Medical Career:
      allowed_periods:
      - R1
      - G1
      max_seats: 15
      requires_dedicated_teacher: true
    Sports Med:
      max_sections_per_period: 1
gemini:
  max_tokens: 2000
  model: gemini-2.0-flash
  temperature: 0.1
  top_k: 1
  top_p: 0.1
logging:
  format: '%(asctime)s [%(levelname)s] %(name)s: %(message)s'
  level: INFO
milp:
  memory_percentage: 0.95
  mip_gap: 0.01
  threads: -1
  time_limit: 25200
optimization:
  actions:
    add_threshold: 1.3
    ideal_class_utilization: 0.85
    max_changes_per_iteration: 10
    max_merge_ratio: 1.3
    max_sections_to_merge: 2
    min_enrollment_percentage: 0.2
    min_split_ratio: 0.4
    min_viable_utilization: 0.3
    split_threshold: 1.2
  utilization:
    max_target: 1.1
    min_acceptable: 0.7
    min_target: 0.7
    optimal_max: 1.05
    optimal_min: 0.85
    remove_threshold: 0.65
paths:
  base_data: data/base
  logs: logs
  runs: data/runs
pipeline:
  ai_provider: gemini
  allow_heuristic_fallback: false
  max_iterations: 10
  save_intermediate_results: true
synthetic_data:
  sizes:
    large: 500
    medium: 125
    small: 25
